/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainForm;

import Connection.konek;
import javax.swing.ImageIcon;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import sun.util.calendar.LocalGregorianCalendar.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rizki Eka Mawardewi (201643500556).
 */
public class FormUtamaSA extends javax.swing.JFrame {
    
    //Connection conn;
    JasperReport JasReport;
    JasperPrint JasPrint;
    Map param = new HashMap();
    JasperDesign JasDes;

    /**
     * Creates new form FormAdmin
     */
    public FormUtamaSA() {
        initComponents();
        ImageIcon ico = new ImageIcon("src/Images/logo-astra-motor-2015 - Copy.jpg");
        setIconImage(ico.getImage());
        this.setLocationRelativeTo(null);
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
        new Thread(){
            public void run(){
                while(true){
                Calendar kal = new GregorianCalendar();
                int tahun = kal.get(Calendar.YEAR);
                int bulan = kal.get(Calendar.MONTH)+1;
                int hari = kal.get(Calendar.DAY_OF_MONTH);
                int jam = kal.get(Calendar.HOUR_OF_DAY);
                int menit = kal.get(Calendar.MINUTE);
                int detik = kal.get(Calendar.SECOND);
                String tanggal = hari + "-"+bulan+"-"+tahun;
                String waktu1 = jam + ":"+menit+":"+detik;
                String waktu2 = jam + ":"+menit+":"+detik;
                jLabel2.setText(tanggal);
                jLabel3.setText(waktu1);
                }
            }
        }.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_mekanik = new javax.swing.JMenu();
        dt_mekanik = new javax.swing.JMenuItem();
        menu_pelanggan = new javax.swing.JMenu();
        dt_pelanggan = new javax.swing.JMenuItem();
        menu_kendaraan = new javax.swing.JMenu();
        dt_kendaraan = new javax.swing.JMenuItem();
        menu_part = new javax.swing.JMenu();
        dt_part = new javax.swing.JMenuItem();
        menu_service = new javax.swing.JMenu();
        ts_service = new javax.swing.JMenuItem();
        menu_rpt = new javax.swing.JMenu();
        rpt_mekanik = new javax.swing.JMenuItem();
        rpt_dtpelanggan = new javax.swing.JMenuItem();
        rpt_dtkendaraan = new javax.swing.JMenuItem();
        rpt_tsservice = new javax.swing.JMenuItem();
        menu_logout = new javax.swing.JMenu();

        jMenuItem6.setText("jMenuItem6");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Admin");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1381, 776));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1381, 776));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TANGGAL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 710, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JAM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 730, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 700, 80, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SA1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 776));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 750));

        menu_mekanik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mechanic_20px.png"))); // NOI18N
        menu_mekanik.setText("Data Mekanik");
        menu_mekanik.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        dt_mekanik.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        dt_mekanik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mechanic_20px.png"))); // NOI18N
        dt_mekanik.setText("Data Mekanik");
        dt_mekanik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_mekanikActionPerformed(evt);
            }
        });
        menu_mekanik.add(dt_mekanik);

        jMenuBar1.add(menu_mekanik);

        menu_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer_20px.png"))); // NOI18N
        menu_pelanggan.setText("Data Pelanggan");
        menu_pelanggan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        dt_pelanggan.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        dt_pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customer_20px.png"))); // NOI18N
        dt_pelanggan.setText("Data Pelanggan");
        dt_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_pelangganActionPerformed(evt);
            }
        });
        menu_pelanggan.add(dt_pelanggan);

        jMenuBar1.add(menu_pelanggan);

        menu_kendaraan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/motorcycle_20px.png"))); // NOI18N
        menu_kendaraan.setText("Data Kendaraan");
        menu_kendaraan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        dt_kendaraan.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        dt_kendaraan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/motorcycle_20px.png"))); // NOI18N
        dt_kendaraan.setText("Data Kendaraan");
        dt_kendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_kendaraanActionPerformed(evt);
            }
        });
        menu_kendaraan.add(dt_kendaraan);

        jMenuBar1.add(menu_kendaraan);

        menu_part.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/toolbox_20px.png"))); // NOI18N
        menu_part.setText("Data Sparepart");
        menu_part.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        dt_part.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        dt_part.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/toolbox_20px.png"))); // NOI18N
        dt_part.setText("Data Sparepart");
        dt_part.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dt_partActionPerformed(evt);
            }
        });
        menu_part.add(dt_part);

        jMenuBar1.add(menu_part);

        menu_service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maintenance_20px.png"))); // NOI18N
        menu_service.setText("Service Motor");
        menu_service.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        ts_service.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        ts_service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/transaction_approved_20px.png"))); // NOI18N
        ts_service.setText("Transaksi Service Motor");
        ts_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_serviceActionPerformed(evt);
            }
        });
        menu_service.add(ts_service);

        jMenuBar1.add(menu_service);

        menu_rpt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graph_report_20px.png"))); // NOI18N
        menu_rpt.setText("Report");
        menu_rpt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        rpt_mekanik.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        rpt_mekanik.setText("Report Data Mekanik");
        rpt_mekanik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt_mekanikActionPerformed(evt);
            }
        });
        menu_rpt.add(rpt_mekanik);

        rpt_dtpelanggan.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        rpt_dtpelanggan.setText("Report Data Pelanggan");
        rpt_dtpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt_dtpelangganActionPerformed(evt);
            }
        });
        menu_rpt.add(rpt_dtpelanggan);

        rpt_dtkendaraan.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        rpt_dtkendaraan.setText("Report Data Kendaraan");
        rpt_dtkendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt_dtkendaraanActionPerformed(evt);
            }
        });
        menu_rpt.add(rpt_dtkendaraan);

        rpt_tsservice.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
        rpt_tsservice.setText("Report Transaksi Service Motor");
        rpt_tsservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpt_tsserviceActionPerformed(evt);
            }
        });
        menu_rpt.add(rpt_tsservice);

        jMenuBar1.add(menu_rpt);

        menu_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shutdown_20px.png"))); // NOI18N
        menu_logout.setText("Logout");
        menu_logout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dt_mekanikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_mekanikActionPerformed
        // TODO add your handling code here:
        DataMekanik dm = new DataMekanik();
        dm.show();
        this.dispose();
    }//GEN-LAST:event_dt_mekanikActionPerformed

    private void dt_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_pelangganActionPerformed
        // TODO add your handling code here:
        DataPelanggan dpl = new DataPelanggan();
        dpl.show();
        this.dispose();
    }//GEN-LAST:event_dt_pelangganActionPerformed

    private void dt_kendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_kendaraanActionPerformed
        // TODO add your handling code here:
        DataKendaraan dk = new DataKendaraan();
        dk.show();
        this.dispose();
    }//GEN-LAST:event_dt_kendaraanActionPerformed

    private void dt_partActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dt_partActionPerformed
        // TODO add your handling code here:
        DataSparepartView dsv = new DataSparepartView();
        dsv.show();
        this.dispose();
    }//GEN-LAST:event_dt_partActionPerformed

    private void ts_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_serviceActionPerformed
        // TODO add your handling code here:
        TransaksiService ts = new TransaksiService();
        ts.show();
        this.dispose();
    }//GEN-LAST:event_ts_serviceActionPerformed

    private void rpt_mekanikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt_mekanikActionPerformed
        // TODO add your handling code here:
        try {
            //File file = new File("src/Laporan/Lap_Mekanik.jrxml");
            InputStream file = getClass().getResourceAsStream("/Laporan/Lap_Mekanik.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.clear();
            JasReport = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasReport, param, konek.koneksiDb());
            JasperViewer.viewReport(JasPrint, false);
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rpt_mekanikActionPerformed

    private void rpt_dtpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt_dtpelangganActionPerformed
        // TODO add your handling code here:
        try {
            //File file = new File("src/Laporan/Lap_Pelanggan.jrxml");
            InputStream file = getClass().getResourceAsStream("/Laporan/Lap_Pelanggan.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.clear();
            JasReport = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasReport, param, konek.koneksiDb());
            JasperViewer.viewReport(JasPrint, false);
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rpt_dtpelangganActionPerformed

    private void rpt_dtkendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt_dtkendaraanActionPerformed
        // TODO add your handling code here:
        try {
            //File file = new File("src/Laporan/Lap_Kendaraan.jrxml");
            InputStream file = getClass().getResourceAsStream("/Laporan/Lap_Kendaraan.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.clear();
            JasReport = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasReport, param, konek.koneksiDb());
            JasperViewer.viewReport(JasPrint, false);
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rpt_dtkendaraanActionPerformed

    private void menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_logoutMouseClicked
        // TODO add your handling code here:
        FormLogin fl = new FormLogin();
        fl.show();
        this.dispose();
        JOptionPane.showMessageDialog(null, "Anda Berhasil Logout");
    }//GEN-LAST:event_menu_logoutMouseClicked

    private void rpt_tsserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpt_tsserviceActionPerformed
        // TODO add your handling code here:
        try {
            //File file = new File("src/Laporan/Lap_Service.jrxml");
            InputStream file = getClass().getResourceAsStream("/Laporan/Lap_Service.jrxml");
            JasDes = JRXmlLoader.load(file);
            param.clear();
            JasReport = JasperCompileManager.compileReport(JasDes);
            JasPrint = JasperFillManager.fillReport(JasReport, param, konek.koneksiDb());
            JasperViewer.viewReport(JasPrint, false);
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_rpt_tsserviceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtamaSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtamaSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtamaSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtamaSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtamaSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dt_kendaraan;
    private javax.swing.JMenuItem dt_mekanik;
    private javax.swing.JMenuItem dt_part;
    private javax.swing.JMenuItem dt_pelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menu_kendaraan;
    private javax.swing.JMenu menu_logout;
    private javax.swing.JMenu menu_mekanik;
    private javax.swing.JMenu menu_part;
    private javax.swing.JMenu menu_pelanggan;
    private javax.swing.JMenu menu_rpt;
    private javax.swing.JMenu menu_service;
    private javax.swing.JMenuItem rpt_dtkendaraan;
    private javax.swing.JMenuItem rpt_dtpelanggan;
    private javax.swing.JMenuItem rpt_mekanik;
    private javax.swing.JMenuItem rpt_tsservice;
    private javax.swing.JMenuItem ts_service;
    // End of variables declaration//GEN-END:variables
}
